[project]
name = "sc"
version = "0.1.1"
description = "Sensor chart viewing utility"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.7",
]

[project.scripts]
scx = "sc:main"
